### PR TITLE
Setup dependencies for plasticity material model

### PR DESCRIPTION
**Pull request by saibalde**
-   Make Kokkos and MPI universal requirements for all builds
-   Use Kokkos version 4 since p3a requires Kokkos_SIMD.hpp
-   Use Trilinos version 14 since it supplies Kokkos version 4
-   Add scripts for installing mpicpp and p3a

### CODE REVIEW

**Comment by nmm0** [comment]
The CI errors are not because of your PR, looks like our images ubuntu package upgraded from gcc 11.1 to gcc 11.4

**Comment by saibalde** [comment]
Thanks for pointing this out! I'll roll back my last commit, and test specifying v11.4.0 in the spack setup.

**Review by nmm0 — COMMENTED** [review]
Can you try on https://github.com/NimbleSM/NimbleSM/pull/346/files#diff-036bef88c67d9e7cee1c802d44f6917d3e5909b5dc2f3fc6a41c8a1bce8453ebL37:

```dockerfile
RUN apt-get update \
  && apt-get install -y \
     gcc-11=11.4.0-2ubuntu1~20.04 \
     g++-11=11.4.0-2ubuntu1~20.04 \
     gfortran-11=11.4.0-2ubuntu1~20.04 \
     cmake-data=3.26.4-0kitware1ubuntu20.04.1 \
     cmake=3.26.4-0kitware1ubuntu20.04.1 \
     pkg-config \
     libncurses5-dev \
     m4 \
     perl \
  && rm -rf /var/lib/apt/lists/*
```

This is doing two things:
1. Pinning the gcc version to be 11.4 in case the apt package gets updated again
2. Updating the pinned cmake version from 3.21.3 to 3.26.4 since new Trilinos requires a newer CMake

**Comment by nmm0** [comment]
@saibalde Can you rebase on the latest changes? I merged in some logging stuff that might give us a better indication of the error

**Comment by nmm0** [comment]
@saibalde I updated the ArborX version. I think that did the trick!

**Comment by saibalde** [comment]
Thanks Nic!

**Review by stmcgovern — APPROVED** [review]
LGTM. After this, ready to test plasticity branch.

**Pull request merged**
