### PR TITLE
Re-organize 'test' directory

### LINKED ISSUE #199: Re-organize directories of tests

### PR DESCRIPTION
**Pull request by uhetmaniuk**
Closes #199

### CODE REVIEW

**Comment by uhetmaniuk** [comment]
- A lot of files have been moved without changes. They appear when the folder is moved to another location.
- Files to review: `test/CMakeLists.txt`, `test/contact/CMakeLists.txt`, `test/dynamics/CMakeLists.txt`, `test/quasistatic/CMakeLists.txt`

**Comment by uhetmaniuk** [comment]
@rjones-sandia @nmm0 
Do you also get an error when trying to view the files changed on GitHub ?

**Comment by nmm0** [comment]
> @rjones-sandia @nmm0
> Do you also get an error when trying to view the files changed on GitHub ?

Yeah I can't see them, I get error 500. I think it's because too many files got changed?

**Comment by uhetmaniuk** [comment]
@nm0
I could split it in 3-4 PRs. What do you think?

**Pull request closed without merging**
