### PR TITLE
Revive uq

### PR DESCRIPTION
**Pull request by rjones-sandia**
Made refactored UQ code fully functional and tested with a benchmark.

### CODE REVIEW

**Comment by uhetmaniuk** [comment]
@rjones-sandia @hnkolla 
I have updated the CI to test with and without UQ.
When testing with UQ, the configuration is complaining

CMake Error: File /home/runner/work/NimbleSM/NimbleSM/test/uq/uq_wave/uq_wave.gold.e does not exist.

Did you forget to commit the gold file maybe?

**Review by uhetmaniuk — APPROVED** [review]
Looks good.

**Comment by rjones-sandia** [comment]
I'll let Hemanth know he can take a look and merge later today. Thanks for the help.

**Comment by rjones-sandia** [comment]
From Hemanth:
I went through the code, while also comparing with the previous implementation as a reference to make sure all steps are in place. This looks good, the design is much better, great job by Ulrich and you. Few things I spotted:
The strategy of having nimble_uq_data_model and nimble_uq_block as derived classes is a great design. See the wisdom behind it now.
nimble_uq_model_data.cc, line 94: Could this instead be int ndims = mesh_.GetDim();
In the main time integrator loop the KinematicBCs are applied after the displacement update and before ComputeInternalForce. In the previous implementation this second BC application was done after the second velocity update by half_delta_t. Is this deliberate?
It looks good and I didn't spot any major things. Whatever residual bugs ought to be minor.

Hemanth.

**Comment by rjones-sandia** [comment]
re: mesh_.GetDim(), good catch. it's done

re: kinematic_bcs, I think the current implementation is correct and what we had before wasn't as accurate for time-independent bc (the common case)  -- in any case it seems that UQ is consistent with what's going on in "main"

**Pull request merged**
