### PR TITLE
#57: bvhcontactmanager-gcc-9-compilation

### LINKED ISSUE #57: BvhContact manager gcc 9 compilation
Compilation fails on GCC 9

### PR DESCRIPTION
**Pull request by nmm0**
Closes #57

### CODE REVIEW

**Comment by nmm0** [comment]
Minor changes to make sure this compiles with gcc 9

**Review by japlews — APPROVED** [review]

**Comment by japlews** [comment]
Tests passed so I pushed. Sorry bout that! Mark your PRs as "draft" if they're WIP. Thanks.

**Comment by nmm0** [comment]
> Tests passed so I pushed. Sorry bout that! Mark your PRs as "draft" if they're WIP. Thanks.

Actually wasn't a draft I forgot to change the title after I unmarked as draft. Thanks!

**Comment by japlews** [comment]
Got it. Funny that Github doesn’t do this automatically...

On Aug 3, 2020, at 2:28 PM, Nicolas Morales <notifications@github.com<mailto:notifications@github.com>> wrote:



Tests passed so I pushed. Sorry bout that! Mark your PRs as "draft" if they're WIP. Thanks.

Actually wasn't a draft I forgot to change the title after I unmarked as draft. Thanks!

**Pull request merged**
