### PR TITLE
WIP: build with Kokkos no MPI

### LINKED ISSUE #22: Cannot build with Kokkos and without MPI support
`nimble_kokkos.cc` depends on nimble.mpi.utils.h, and the code is designed around MPI support. See MPI code around line 75, 100, 140, 345, 380, 550: https://github.com/NimbleSM/NimbleSM/blob/ff10fd9995c2703e051c8102fc9ea2b36cb1fcec/src/nimble_kokkos.cc#L71

This makes NimbleSM unable to work with Kokkos without MPI enabled.

### PR DESCRIPTION
**Pull request by uhetmaniuk**
Code does not compile with Kokkos and without MPI. Several statements need to be protected.

Closes #22

### CODE REVIEW

**Comment by rjones-sandia** [comment]
build for me with -DUSE_PURE_MPI=TRUE -DNIMBLE_HAVE_EXODUS=TRUE
good to go

**Comment by uhetmaniuk** [comment]
@rjones-sandia Thank you for being so responsive in your reviews.
This PR was incomplete as the test list needs to be reduced (for Kokkos without MPI). I will create a follow-up issue and check that everything else is fine.

**Comment by japlews** [comment]
Was the PR designated a draft? Let's make sure WIP doesn't get pushed to the master branch.

**Comment by rjones-sandia** [comment]
Hi  Julia,

  ?that was my fault. I was confused what was being put into each PR.


Does master still build for you? That's my main concern since I thought the changes to the CMake files were done and tested but perhaps they weren't


sorry,

Reese



======================================================================
"the second law is just a fancy way of saying things are going from bad to worse" -- Eeyore
"nah, they are just getting more interesting" -- Piglet
======================================================================
Reese Jones (925) 294-4744
________________________________

**Comment by rjones-sandia** [comment]
??ok, reading Ulrich's email it clearly wasn't ready.

I can revert the merge (assuming that functionality works) or let Ulrich patch with another "issue"


R


======================================================================
"the second law is just a fancy way of saying things are going from bad to worse" -- Eeyore
"nah, they are just getting more interesting" -- Piglet
======================================================================
Reese Jones (925) 294-4744
________________________________

**Comment by japlews** [comment]
Lemme check. Reverting is easy enough if we need to!

Otherwise, it’s not a showstopper. We can just hang tight for the fix.

On Jul 6, 2020, at 2:38 PM, rjones-sandia <notifications@github.com<mailto:notifications@github.com>> wrote:


??ok, reading Ulrich's email it clearly wasn't ready.

I can revert the merge (assuming that functionality works) or let Ulrich patch with another "issue"


R


======================================================================
"the second law is just a fancy way of saying things are going from bad to worse" -- Eeyore
"nah, they are just getting more interesting" -- Piglet
======================================================================
Reese Jones (925) 294-4744
________________________________

**Comment by uhetmaniuk** [comment]
@rjones-sandia @japlews It should build but the testing will fail.
The code will throw a runtime error as it can not initialize the class nimble::MPIContainer.
So we should not be losing any capability.
Is anyone running with Kokkos standalone and no MPI?

**Comment by rjones-sandia** [comment]
?not that I know of.


Nic kokkos standalone w/o MPI is not a case you're interested in?

Reese


======================================================================
"the second law is just a fancy way of saying things are going from bad to worse" -- Eeyore
"nah, they are just getting more interesting" -- Piglet
======================================================================
Reese Jones (925) 294-4744
________________________________

**Comment by japlews** [comment]
Just confirming that my builds (Kokkos+MPI with/without CUDA) are functional.

**Comment by nmm0** [comment]
@rjones-sandia It's not a case I need but at some point I thought fixed that crash involving MPIContainer. I think it might be in my PR, I'll check

**Comment by uhetmaniuk** [comment]
@rjones-sandia @nmm0 I just submitted a pull request #27 that addresses that runtime error.

**Pull request merged**
