### PR TITLE
#344: Make GitHub NimbleSM CI work

### LINKED ISSUE #344: Make GitHub NimbleSM CI work

### PR DESCRIPTION
**Pull request by pierrepebay**

### CODE REVIEW

**Comment by pierrepebay** [comment]
Removing the specification of the hdf5 version has lead to all checks passing.
Screenshot 2023-07-12 at 10 12 44
Re-running to double check.
https://github.com/NimbleSM/NimbleSM/actions/runs/5524197463

**Review by stmcgovern — APPROVED** [review]
LGTM

**Review by nmm0 — CHANGES_REQUESTED** [review]
Can we change the spack version in the dockerfile:

`git clone --depth 1 --branch "v0.20.1" https://github.com/spack/spack.git`

https://github.com/NimbleSM/NimbleSM/blob/develop/ci/ubuntu20.04-gcc11-x64.dockerfile#L51

**Review by stmcgovern — APPROVED** [review]
LGTM.

**Review by nmm0 — APPROVED** [review]
Great work!

**Pull request merged**
