### PR TITLE
Rebase develop refactor

### LINKED ISSUE #218: Rebase branch
Rebase 'develop-refactor' before merge

### PR DESCRIPTION
**Pull request by uhetmaniuk**
Closes #218 

This PR includes all the changes to convert the code with multiple executables into a code with one executable.
All the major changes have been previously approved individually.

### CODE REVIEW

**Comment by uhetmaniuk** [comment]
@nmm0 @japlews @rjones-sandia 
This pull request would update the 'develop' branch with the latest code that generates only one executable.
Please run your local tests (that go beyond the GitHub CI) for your review.
- @japlews Since last week, I have done some cosmetic changes and I have incorporated the UQ component. I believe that it should not impact your simulations. Please let me know if any of your tests fails.
- @nmm0 Please have a look at the VT initialization and how the function 'runInEpochCollective' is called. I believe it is equivalent to what you had in the 'develop'. Please let me know if you see any mistake.
Thanks.

**Review by rjones-sandia — APPROVED** [review]
Based on previous incremental reviews I approve this one.
Nic and Julia's oks are pending.

**Review by japlews — APPROVED** [review]
Builds for me and all tests pass.

**Review by nmm0 — CHANGES_REQUESTED** [review]
Sorry this took so long. Unfortunately this kind of breaks the bvh build because of some recent changes to VT (there are also a few typos but those are minor). I think I should set up a PR after this is merged to reconcile the BVH build. Can you fix the typos and then we'll get the rest working in another PR?)

Please see the attached patch for typos
[develop-refactor.patch.tar.gz](https://github.com/NimbleSM/NimbleSM/files/6314297/develop-refactor.patch.tar.gz)

**Comment by uhetmaniuk** [comment]
@nmm0  Done.

**Comment by uhetmaniuk** [comment]
@nm0 
Do you mind approving the PR? or allowing me to merge? 
Thank you.

After that, I cleaned the list of branches.

**Review by nmm0 — APPROVED** [review]
Looks good! We will still need to create another PR to do bvh fixes

**Pull request merged**
