### PR TITLE
CMake: add RUNTIME DESTINATION to installed executables

### PR DESCRIPTION
**Pull request by japlews**
Fix CMake install by adding a runtime destination.

### CODE REVIEW

**Comment by japlews** [comment]
I'm confused. Why would changing CMake install settings break tests? Did something else change under me?

Julia

**Comment by nmm0** [comment]
> I'm confused. Why would changing CMake install settings break tests? Did something else change under me?
> 
> Julia

I think our Trilinos builds are broken right now -- it's not you. I merged in @uhetmaniuk 's PR for updating the trilinos build. If you rebase on develop now I think it should fix the problem

**Review by nmm0 — APPROVED** [review]
Looks good! I think just rebase on develop since Ulrich fixed the trilinos issue for CI

**Comment by japlews** [comment]
@nmm0 Gotcha, just merged in develop so we'll try it again.

**Pull request merged**
