### PR TITLE
material: refactor parsing/parameters to use strings and maps

### LINKED ISSUE #46: Material parsing uses char* and fixed-length arrays instead of STL
This is in the name of running on the GPU; however, refactoring to copy-construct a material instance on the device is straightforward, rather than relying on reading strings.

### PR DESCRIPTION
**Pull request by japlews**
Closes #46.

### CODE REVIEW

**Review by rjones-sandia — APPROVED** [review]
Cleaner, like it!

**Comment by rjones-sandia** [comment]
FYI CI is saying some checks (build) are failing.

**Comment by japlews** [comment]
Working on it…hence the draft status. Thank you!

On Jul 27, 2020, at 2:01 PM, rjones-sandia <notifications@github.com<mailto:notifications@github.com>> wrote:



FYI CI is saying some checks (build) are failing.

**Comment by rjones-sandia** [comment]
?thanks Julia,

   sorry I'm still getting the hang of when to take actions with git hub.

Reese


======================================================================
"the second law is just a fancy way of saying things are going from bad to worse" -- Eeyore
"nah, they are just getting more interesting" -- Piglet
======================================================================
Reese Jones (925) 294-4744
________________________________

**Pull request merged**
