### PR TITLE
161 add swap function (Depends on PR #159 - Needs a rebase)

### LINKED ISSUE #161: Add swap state function to nimble_kokkos::ModelData

### PR DESCRIPTION
**Pull request by uhetmaniuk**
Closes #161

### CODE REVIEW

**Review by rjones-sandia — COMMENTED** [review]
looks good -- most changes I see are from earlier PRs

I "approve" this PR but I'm only leaving a comment to make sure an automatic merge won't compound the minor conflict issues.

Let me know when to change to "Approve"

**Comment by uhetmaniuk** [comment]
@rjones-sandia 
I need to see how to make "nested" PRs with Github. 
A rebase would help but I was hoping for an automatic way.

**Review by rjones-sandia — COMMENTED** [review]
should I "approve" at this point or wait? I'm happy to whichever makes it easier for you.
thanks, R

**Comment by uhetmaniuk** [comment]
@rjones-sandia 
Maybe wait.

**Pull request closed without merging**
